# Generated by Django 4.2 on 2023-04-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="click",
            field=models.IntegerField(default=0, verbose_name="click"),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="teacher"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="create_time"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="update_time"),
        ),
    ]
