# Generated by Django 4.2 on 2023-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_click_course_teacher_alter_course_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="comment",
            field=models.TextField(
                default="No comment provided", verbose_name="comment"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                default="Beginner",
                max_length=50,
                verbose_name="difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
