# Generated by Django 4.2 on 2023-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_comment_course_difficulty_alter_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
                verbose_name="difficulty",
            ),
        ),
    ]
